### ISSUE TITLE
How to custom the tabbar selectedItem's background color?

### ISSUE THREAD

**Issue by james-bltg** [AlbGarciam/AnimatedTabBar#3]
When I trying to apply this in my little Pj, I tried to custom the selectedItem's backgroundColor.
But I have no idea how to work it out.

Could you help me anyway?

Thanks

**Comment by AlbGarciam** [comment]
@MorLightJ There is no way to do that, because the way to notify the user that an item is selected is to have the text visible.

You can change text color or dot color by calling:
```swift 
AnimatedTabBarAppearance.shared.dotColor = UIColor.red
AnimatedTabBarAppearance.shared.textColor = UIColor.red
```

Hope it helps you :)

**Comment by james-bltg** [comment]
It Works.
I got a new problem,  when I specify viewcontrollers for tabbar's controllers, it won't render until I tapped the tabbarItem.

the code here:

var items = [
				 AnimatedTabBarItem(icon: UIImage(named: "home") ?? UIImage(),
									title: "Home", controller: Home.create() ?? Home()),
				 AnimatedTabBarItem(icon: UIImage(named: "search") ?? UIImage(),
									title: "Stats", controller: Stats())
			   ]

I made the initialIndex with 0, but the Home view didn't render,unless I tapped the Home tabbarItem.

How should I do to make it right??

**Comment by AlbGarciam** [comment]
@MorLightJ There was an issue on the library. I have noticed on my app and I have fixed it 👍 

Thanks for reporting it
